#!/usr/bin/env python3
'''Generate pbe.cl (f32 + f64 PBE vxc) from libxc maple2c gga_x_pbe.c / gga_c_pbe.c.'''
import re
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent
LIBXC = pathlib.Path('/tmp/libxc/src/maple2c/gga_exc')

HEADER = '''// Auto-generated by generate_pbe_cl.py — do not edit by hand.
// libxc maple2c PBE exchange + correlation (func_vxc_unpol), unpolarized only.

#ifndef PBE_CL_GENERATED
#define PBE_CL_GENERATED

#define PBE_KAPPA 0.804
#define PBE_MU 0.2195149727645171
#define PBE_GAMMA 0.031090690869654895
#define PBE_BETA 0.06672455060314922
#define PBE_BB 1.0
#define PBE_TSCALE 1.0
#define PBE_DENS_THRESHOLD 1.0e-14
#define PBE_ZETA_THRESHOLD 0.0

#define PBE_CBRT3 1.4422495703074089
#define PBE_CBRTPI 1.4645918875615231
#define PBE_CBRT2 1.2599210498948732
#define PBE_CBRT4 1.5874010519681994
#define PBE_CBRT6 1.8171205928321397

'''

FOOTER = '''
#endif
'''

PIECEWISE_HELPERS = '''
inline {R} pbe_pw3_{S}({R} c, {R} a, {R} b) {{ return (c != ({R})0.0) ? a : b; }}
inline {R} pbe_pw5_{S}({R} t10, {R} t11, {R} t12, {R} t13, {R} d) {{
    if (t10 != ({R})0.0) return t11;
    if (t12 != ({R})0.0) return t13;
    return d;
}}
'''


def _extract_vxc_body(c_text):
    m = re.search(r'func_vxc_unpol\([^)]*\)\s*\{(.*?)^\}', c_text, re.S | re.M)
    if not m:
        raise RuntimeError('func_vxc_unpol not found')
    body = m.group(1)
    decl_parts = []
    lines = []
    for line in body.splitlines():
        s = line.strip()
        if not s or s.startswith('assert') or 'out->' in s or s.startswith('gga_'):
            continue
        if s.startswith('params'):
            continue
        if s.startswith('double '):
            decl_parts.append(s[len('double '):].rstrip(';'))
            continue
        lines.append(line)
    decl = f"PLACEHOLDER {', '.join(decl_parts)};" if decl_parts else ''
    return decl, '\n'.join(lines)


def _transpile_body(decl, body, real, suffix):
    r = real
    lit = 'f' if suffix == 'f32' else ''
    decl = decl.replace('float', r).replace('PLACEHOLDER', r)
    body = body.replace('double', r)
    body = re.sub(r'0\.(\d+)e([+-]?\d+)', lambda m: f'{float(m.group(0))}{lit}', body)
    body = body.replace('0.e0', f'0.0{lit}')
    body = body.replace('rho[0]', 'rho')
    body = body.replace('sigma[0]', 'sigma')
    body = body.replace('params->kappa', 'PBE_KAPPA')
    body = body.replace('params->mu', 'PBE_MU')
    body = body.replace('params->gamma', 'PBE_GAMMA')
    body = body.replace('params->beta', 'PBE_BETA')
    body = body.replace('params->BB', 'PBE_BB')
    body = body.replace('params->tscale', 'PBE_TSCALE')
    body = body.replace('p->dens_threshold', 'PBE_DENS_THRESHOLD')
    body = body.replace('p->zeta_threshold', 'PBE_ZETA_THRESHOLD')
    body = body.replace('M_CBRT3', 'PBE_CBRT3')
    body = body.replace('M_CBRTPI', 'PBE_CBRTPI')
    body = body.replace('M_CBRT2', 'PBE_CBRT2')
    body = body.replace('M_CBRT4', 'PBE_CBRT4')
    body = body.replace('M_CBRT6', 'PBE_CBRT6')
    body = body.replace('M_PI * M_PI', f'PBE_PI_{suffix.upper()} * PBE_PI_{suffix.upper()}')
    body = body.replace('M_PI', f'PBE_PI_{suffix.upper()}')
    decl = decl.replace('M_PI', f'PBE_PI_{suffix.upper()}')
    body = body.replace('my_piecewise3(', f'pbe_pw3_{suffix}(')
    body = body.replace('my_piecewise5(', f'pbe_pw5_{suffix}(')
    body = body.replace('xc_log1p(', 'log1p(')
    body = body.replace('xc_expm1(', 'expm1(')
    body = body.replace('POW_1_3(', f'pbe_cbrt_{suffix}(')
    body = body.replace('POW_3_2(', f'pbe_pow32_{suffix}(')
    for name in ('tzk0', 'tvrho0', 'tvsigma0'):
        body = body.replace(name, 'exc_loc' if name == 'tzk0' else ('vrho_loc' if name == 'tvrho0' else 'vsigma_loc'))
        decl = decl.replace(name, 'exc_loc' if name == 'tzk0' else ('vrho_loc' if name == 'tvrho0' else 'vsigma_loc'))
    return decl, body


def _emit_real_block(suffix, real):
    pi = f'3.14159265358979323846{ "f" if suffix=="f32" else ""}'
    helpers = PIECEWISE_HELPERS.format(R=real, S=suffix)
    cbrt = f'#define PBE_PI_{suffix.upper()} {pi}\n'
    x_decl, x_raw = _extract_vxc_body((LIBXC / 'gga_x_pbe.c').read_text())
    c_decl, c_raw = _extract_vxc_body((LIBXC / 'gga_c_pbe.c').read_text())
    x_decl, x_body = _transpile_body(x_decl, x_raw, real, suffix)
    c_decl, c_body = _transpile_body(c_decl, c_raw, real, suffix)

    fn_x = f'''
{helpers}
{cbrt}
inline {real} pbe_cbrt_{suffix}({real} x) {{ return pow(x, ( {real})0.33333333333333333333); }}
inline {real} pbe_pow32_{suffix}({real} x) {{ return pow(x, ( {real})1.5); }}
inline void pbe_x_vxc_{suffix}({real} rho, {real} sigma, {real} *exc, {real} *vrho, {real} *vsigma)
{{
    {x_decl};
{x_body}
    *exc = exc_loc;
    *vrho = vrho_loc;
    *vsigma = vsigma_loc;
}}
'''

    fn_c = f'''
inline void pbe_c_vxc_{suffix}({real} rho, {real} sigma, {real} *exc, {real} *vrho, {real} *vsigma)
{{
    {c_decl};
{c_body}
    *exc = exc_loc;
    *vrho = vrho_loc;
    *vsigma = vsigma_loc;
}}
'''

    kernel = f'''
__kernel void pbe_xc_{suffix}(
    __global const {real} *rho_in,
    __global {real} *exc,
    __global {real} *vrho,
    __global {real} *vsigma,
    int ngrids)
{{
    int igrid = get_global_id(0);
    if (igrid >= ngrids) return;
    {real} rho = rho_in[0 * ngrids + igrid];
    {real} dx = rho_in[1 * ngrids + igrid];
    {real} dy = rho_in[2 * ngrids + igrid];
    {real} dz = rho_in[3 * ngrids + igrid];
    {real} sigma = dx * dx + dy * dy + dz * dz;
    if (rho < ({real})1.0e-10) {{
        exc[igrid] = ({real})0.0;
        vrho[igrid] = ({real})0.0;
        vsigma[igrid] = ({real})0.0;
        return;
    }}
    {real} ex, er, es, ec, cr, cs;
    pbe_x_vxc_{suffix}(rho, sigma, &ex, &er, &es);
    pbe_c_vxc_{suffix}(rho, sigma, &ec, &cr, &cs);
    exc[igrid] = ex + ec;
    vrho[igrid] = er + cr;
    vsigma[igrid] = es + cs;
}}

__kernel void compute_wv_gga_{suffix}(
    __global const {real} *weight,
    __global const {real} *vrho,
    __global const {real} *vsigma,
    __global const {real} *rho_grad,
    __global {real} *wv,
    int ngrids)
{{
    int igrid = get_global_id(0);
    if (igrid >= ngrids) return;
    {real} w = weight[igrid];
    {real} vr = vrho[igrid];
    {real} vs = vsigma[igrid];
    {real} dx = rho_grad[1 * ngrids + igrid];
    {real} dy = rho_grad[2 * ngrids + igrid];
    {real} dz = rho_grad[3 * ngrids + igrid];
    wv[0 * ngrids + igrid] = w * vr;
    wv[1 * ngrids + igrid] = w * ({real})2.0 * vs * dx;
    wv[2 * ngrids + igrid] = w * ({real})2.0 * vs * dy;
    wv[3 * ngrids + igrid] = w * ({real})2.0 * vs * dz;
}}
'''
    fp64_pragma = '#pragma OPENCL EXTENSION cl_khr_fp64 : enable\n' if suffix == 'f64' else ''
    return fp64_pragma + fn_x + fn_c + kernel


def main():
    out = [HEADER]
    out.append(_emit_real_block('f32', 'float'))
    out.append(_emit_real_block('f64', 'double'))
    out.append(FOOTER)
    (ROOT / 'pbe.cl').write_text(''.join(out))
    print('wrote', ROOT / 'pbe.cl')


if __name__ == '__main__':
    main()
